config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  root 'categories#index'

  resources :categories, only: [:show, :index] do
    resources :posts do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :posts

  def most_recent_posts
    self.posts.most_recent
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  validates :body, presence: true

end

app/models/gravatar_link.rb
require 'digest'

class GravatarLink
  attr_reader :email

  def initialize(email)
    @email = email
  end

  def link
    "https://www.gravatar.com/avatar/#{email_hash}"
  end

  def self.for_email(email)
    new(email).link
  end


  private

  def email_hash
    @email_hash ||= Digest::MD5.hexdigest(email)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc) }
  scope :most_recent, -> { order(created_at: :desc).limit(3) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  validates :first_name, :last_name, :public_name, presence: true
  validates :public_name, uniqueness: true

  def gravatar_link
    @gravatar_link ||= GravatarLink.for_email(self.email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = CategoryDecorator.decorate_collection(Category.all)
  end

  def show
    if category = Category.find_by_id(params[:id])
      @category = CategoryDecorator.decorate(category)
    else
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(post_params)
    if comment.save
      flash[:success] = 'Your comment has been successfully added!'
    else
      flash[:danger] = 'Your comment could not be added.'
    end
    redirect_to category_post_path(category_id: post.category.id, id: post.id)
  end

  private

  def post_params
    user_and_post = {author_id: current_user.id, post_id: params[:post_id]}
    params.require(:comment).permit(:body).merge!(user_and_post)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def new
    @post = Post.new
  end

  def create
    nps = NewPostService.new(user: current_user, params: params)
    if nps.call
      redirect_to category_post_path(category_id: nps.post.category_id, id: nps.post.id)
    else
      render :new
    end
  end

  def show
    @post = PostDecorator.decorate(Post.find(params[:id]))
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :public_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :public_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/categories/_all_posts.html.slim
- category.posts.each do |post|
  = render partial: 'posts/preview', locals: {post: post.decorate}

app/views/categories/_recent_posts.html.slim
- category.most_recent_posts.each do |post|
  = render partial: 'posts/preview', locals: {post: post.decorate}

app/views/categories/index.html.slim
- @categories.each do |category|
  .row
    .col-xs-12
      div.category-title
        h2 = category.name
        .pull-right.view-all-posts = link_to category.view_all_text, category_path(category)
      - if category.most_recent_posts.any?
        = render partial: 'categories/recent_posts', locals: {category: category}
      - else
        h5.text-center There are no posts for this category.
  

app/views/categories/show.html.slim
.row
  .col-xs-12
    .category-title
      h2 = @category.name
      .pull-right
        - if current_user
          = link_to 'New Post', new_category_post_path(category_id: @category.id), class: 'btn btn-primary new-post-btn'
        - else
          = link_to 'New Post', '#', class: 'btn btn-primary new-post-btn sign-up-btn'
.row
  .col-xs-12
    - if @category.posts.any?
      = render partial: 'categories/all_posts', locals: {category: @category}
    - else
      h5.text-center There are no posts for this category.

app/views/comments/_comment.html.slim
.row
  .col-xs-12
    p = comment.body
    p = comment.published_by

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ViaBoards
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Nunito:300,400'
  body
    
    .container
      .row.header
        = render partial: 'shared/header'
      
    .container.page-body
      .row
        .col-xs-12
          = yield

  - if !current_user
    = render partial: 'shared/devise_modals'

app/views/posts/_preview.html.slim
= link_to category_post_path(category_id: post.category.id, id: post.id), class: 'html-link' do
  .row
    .col-sm-2.text-center.hidden-xs
      span.timestamp = post.created_at
    .col-sm-8.col-xs-12
      h4.post-title = post.title
      p.post-author
        span = post.published_by
        span.visible-xs.inline = " on #{post.created_at}"
      p.post-summary = post.body.truncate(100)
      
      
    .col-sm-2.text-right.hidden-sm.hidden-xs
      .btn.btn-primary.read-more Read Post

app/views/posts/new.html.slim
h1 New Post

= bootstrap_form_for @post, url: category_posts_path do |f|
  = f.text_field :title
  = f.text_area :body, rows: 10
  = f.submit 'Create Post', class: 'btn btn-primary'

app/views/posts/show.html.slim
.row
  .col-sm-3.text-center
    img.img-responsive.img-circle.gravatar src="#{@post.author.gravatar_link}" alt="#{@post.author.public_name}"
    p = @post.published_by
    p.timestamp= @post.created_at
    
  .col-sm-8
    h1.category-title = @post.title

    p = @post.body

    h3.category-title Comments
    - @post.comments.each do |comment|
      = render partial: 'comments/comment', locals: {comment: comment.decorate}

    - if current_user
      = bootstrap_form_for @post.comments.new, url: category_post_comments_path(category_id: @post.category.id, post_id: @post.id) do |f|
        = f.text_area :body, label: 'Add a Comment'
        = f.submit 'Add Comment', class: 'btn btn-primary'
    - else
      .text-center
        h5 You need to create an account to comment
        = link_to 'Create Account', '#', class: 'btn btn-primary sign-up-btn'
        = link_to 'Sign In', '#', class: 'btn btn-link sign-in-btn'
    

app/views/shared/_devise_modals.html.slim
#sign-in-modal.modal.fade.user-session-modal aria-labelledby="Sign up for Viaboards" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      .modal-body
        .row
          .col-sm-4.left
            = image_tag 'https://www.via-trm.com/assets/marketing/logo.png', class: 'img-responsive logo-img'
          
          .col-sm-8.text-center
            = render partial: 'devise/sessions/new'

#sign-up-modal.modal.fade.user-session-modal aria-labelledby="Sign in to Viaboards" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  &times;
      .modal-body
        .row
          .col-sm-4.left
            = image_tag 'https://www.via-trm.com/assets/marketing/logo.png', class: 'img-responsive logo-img'
          
          .col-sm-8.text-center
            = render partial: 'devise/registrations/new'

javascript:
  $(document).on('turbolinks:load', function() {
    var signUpModal = $('#sign-up-modal'),
        signInModal = $('#sign-in-modal'),
        signUpBtn = $('.sign-up-btn'),
        signInBtn = $('.sign-in-btn');
    
    signUpBtn.on('click', function(e) {
      e.preventDefault();
      signUpModal.modal('show');
    });
    
    signInBtn.on('click', function(e) {
      e.preventDefault();
      signInModal.modal('show');
    })
  })

app/views/shared/_header.html.slim
.col-sm-2.col-xs-4.logo-container
  = link_to root_path do
    = image_tag 'https://www.via-trm.com/assets/marketing/logo.png', class: 'img-responsive logo-img'

.col-sm-10.col-xs-8.text-right.menu
  - if current_user
    = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-link'
  - else
    = link_to 'Sign In', '#', class: 'btn btn-link sign-in-btn'
    = link_to 'Sign Up', '#', class: 'btn btn-primary sign-up-btn'